### ISSUE TITLE
Delta sensors missing from the desciption

### ISSUE THREAD

**Issue by Ysbrand** [igordockx/HA-Thermia-Genesis-Monitoring#1]
Thanks for the write up and instructions, this made things much easier for me.

A minor thing the 2 delta sensors are missing in the description, not a big deal to create those,but might be useful for others who follow your instructions.

```
sensor.brine_delta_t
sensor.condenser_delta_t
```

**Comment by igordockx** [comment]
Thank you for your feedback Ysbrand;

I modified the readme to include the delta T template code.
